# Generated by Django 5.1.1 on 2024-11-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhobby',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
