# Generated by Django 5.1.1 on 2024-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pictures/'),
            preserve_default=False,
        ),
    ]
